//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyNotes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notas()
        {
            this.Reminder = new HashSet<Reminder>();
            this.Tags = new HashSet<Tags>();
        }
    
        public int idNota { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idEstado { get; set; }
        public bool fijada { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reminder> Reminder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
