//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyNotes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int idReminder { get; set; }
        public Nullable<int> intervalo { get; set; }
        public Nullable<int> idTipoUnidad { get; set; }
        public Nullable<int> idTipoFrecuencia { get; set; }
        public Nullable<int> idNota { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Notas Notas { get; set; }
        public virtual TipoUnidad TipoUnidad { get; set; }
        public virtual TipoFrecuencia TipoFrecuencia { get; set; }
    }
}
