//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyNotes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int idReminder { get; set; }
        public Nullable<int> intervalo { get; set; }
        public Nullable<int> idTipoUnidad { get; set; }
        public Nullable<int> idTipoFrecuencia { get; set; }
        public Nullable<int> idNota { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Notas Notas { get; set; }
        public virtual TipoUnidad TipoUnidad { get; set; }
        public virtual TipoFrecuencia TipoFrecuencia { get; set; }
    }
}
