//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyNotes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StickyNotesEntities : DbContext
    {
        public StickyNotesEntities()
            : base("name=StickyNotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Reminder> Reminder { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TipoFrecuencia> TipoFrecuencia { get; set; }
        public virtual DbSet<TipoUnidad> TipoUnidad { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
