//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyNotes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StickyNotesEntities : DbContext
    {
        public StickyNotesEntities()
            : base("name=StickyNotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Reminder> Reminder { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TipoFrecuencia> TipoFrecuencia { get; set; }
        public virtual DbSet<TipoUnidad> TipoUnidad { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
